---
title: "Randy's Notes on Ataya"
author: "Randy Swaty"
date: '2022-06-13'
output:
  pdf_document: default
  html_document: default
---


# Basic QAQC on Ataya_combineClean.xlsx

Partly a QAQC, but more a way to force me to look more critically

* do acres add up?  Sum of COUNT of "combineClean" sheet = 452589*.222 = 100,474 Acres = Good Enough

## BpS
* does the list of BpSs make sense?  

    *  Southern Appalachian Oak Forest	31.99%
    *  Southern and Central Appalachian Cove Forest	25.16%.  
    *  South-Central Interior Mesophytic Forest	22.56%
    *  Allegheny-Cumberland Dry Oak Forest and Woodland	11.71%
    *  Central Interior and Appalachian Riparian Systems	5.63%
    *  Appalachian (Hemlock-)Northern Hardwood Forest	2.11%
    *  Southern Appalachian Northern Hardwood Forest	0.35%
    *  Open Water	0.23%
    *  Central Interior and Appalachian Floodplain Systems	0.16%
    *  Central Interior and Appalachian Swamp Systems	0.05%
    *  Southern Appalachian Low-Elevation Pine Forest	0.04%
    
*Notes from this list*
* the list of names is OK
* relative amounts raise eyebrows as we'd expect less cove/mesophytic and more oak
* does seem like LANDFIRE mapped too much of the cove forest type, which should be restricted to the "opographically protected areas (e.g. coves, v-shaped valleys, north- and east-facing toe slopes) within highly dissected hills and mountains".  
* the South-Central Interior Mesophytic Forest is not "oaky" either.
* ~42% of the area was mapped as oak types historically

* Does BpS attribute table match when I reprocess? YES
* I have sent remade BPS and EVT maps to Mark Rogers who works on the Ataya for his opinion. 




# Ideas for dealing with suspect LANDFIRE data

* link to Helmbrehct and Blankenship data review paper https://www.conservationgateway.org/ConservationPractices/FireLandscapes/LANDFIRE/Documents/ModifyingLF_DataGuide_V1.pdf
* reclassify if there are credible reasons to
* don't use spatial data.  Can still use BPS models and descriptions to get concepts.
* "lump up" i.e., use group veg or something...can still explore conversion




